### ISSUE TITLE
Add a field that calculates USD value of each trade

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-subgraph#2]
Using some on-chain oracle (chainlink or uniswap, perhaps?), we should calculate the USD value of each trade when it happens and add this to a field in the subgraph.

This will be useful for things like comparing total and 24 hour volumes of markets that are denominated in different tokens.

For example, Volume in Omen is currently sorted by the number of tokens, rather than the USD value, meaning that markets denominated in low value tokens with more decimal places will bubble to the top of volume sorted lists.
What we actually want is for this list to be sorted by USD value.

**Comment by cag** [comment]
Belongs to Omen: https://github.com/protofire/omen-subgraph/issues/27
