### ISSUE TITLE
Create a method to get more accurate 24 hour volume

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-subgraph#3]
Currently, the subgraph calculates 24 hour volume by the current day, rather than the previous 24 hours.
This means that the 24 hour volume appears much lower than it actually is the more recently you have passed into a new day according to the subgraph.

@cag suggested that we make several such windows of time, one per hour (or more?), so that the 24 hour volume data is closer to reality in all cases.

This issue is dependent on #2.

**Comment by cag** [comment]
Belongs to Omen subgraph: https://github.com/protofire/omen-subgraph/issues/26
