### ISSUE TITLE
Case insensitive queries

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-subgraph#4]
All queries to thegraph are currently case sensitive.

This creates a poor user experience on Omen, as most people are not used to interacting with case sensitive search.
For example, a user searching for the market *"Will Ethereum 2.0 Phase 0 launch before 2021?"* might enter `ethereum`, in which case, this market would not be displayed.

We should create a method for case insensitive queries to our subgraph.

Two possible solutions were suggested:

1. @leolower suggested that we add a lowercase copy of the title as a field in the subgraph
2. @cag suggested it would be the same, or less, work to make a PR on The Graph's codebase to allow for case insensitive queries.

**Comment by cag** [comment]
Done here: https://github.com/protofire/omen-subgraph/pull/32
