### ISSUE TITLE
Migrate subgraph to the Gnosis Org

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-subgraph#5]
Right now, the subgraph that Omen (and others?) are using is linked to @cag's personal account.
We should migrate it to the Gnosis org account.

We can use `gnosis/ct` as the new name for the subgraph.

**Comment by auryn-macmillan** [comment]
@cag did this ever happen?

**Comment by cag** [comment]
Right now, Omen's actually using `protofire/omen` in production, and we've been using `gnosis/omen` to stage changes and check the development version of the frontend.

The same is not true for hg-subgraph, which currently lives on my personal account `cag/hg` and `cag/hg-rinkeby`. I'll open an issue in the appropriate repo. This repo needs to be renamed anyway...
