### ISSUE TITLE
Update subgraph to accommodate scalar market changes to the realit.io adapter

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-subgraph#6]
We're planning to update the realit.io adapter to accommodate for scalar markets, see this issue https://github.com/gnosis/realitio-gnosis-proxy/issues/4.

When this happens, we'll need a corresponding change to the subgraph.

**Comment by cag** [comment]
I put an issue in the actual repo: https://github.com/protofire/omen-subgraph/issues/63
